pipeline:
  build:
    image: docker:1.11
#    environment:
#      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker build -t ibm-backend .

services:
  dind:
    image: docker:1.11-dind
#    privileged: true
