pipeline:
  build:
    image: docker:1
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker build -t ibm-backend .

services:
  dind:
    image: docker:1.12-dind
    privileged: true
    # entrypoint: []
    command:
      - "-s"
      - "overlay"
