pipeline:
  build:
    image: docker:1
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - echo $$DOCKER_TOKEN
      - docker build -t ibm-backend .

  tag:
    image: docker:1
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker tag ibm-backend quay.io/ukhomeofficedigital/removals-api:d${DRONE_BUILD_NUMBER}
      - docker tag ibm-backend quay.io/ukhomeofficedigital/removals-api:origin_`echo ${DRONE_BRANCH} | sed -e "s/\//_/g")`
      - docker images

  push:
    image: docker:1
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker push quay.io/ukhomeofficedigital/removals-api:d${DRONE_BUILD_NUMBER}
      - docker push quay.io/ukhomeofficedigital/removals-api:origin_`echo ${DRONE_BRANCH} | sed -e "s/\//_/g")`


services:
  dind:
    image: docker:1-dind
    privileged: true
    command:
      - "-s"
      - "overlay"
