pipeline:
  build:
    image: docker:1
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker build -t ibm-backend .

  tag:
    image: docker:1
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
#      - DOCKER_BRANCH=$(echo ${DRONE_BRANCH} | sed -e "s/\//_/g")
    commands:
      - docker tag ibm-backend quay.io/ukhomeofficedigital/removals-api:d${DRONE_BUILD_NUMBER}
#      - docker tag ibm-backend quay.io/ukhomeofficedigital/removals-api:${DOCKER_BRANCH}
      - docker images

  push:
    image: docker:1
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
#      - export DOCKER_BRANCH=$(echo ${DRONE_BRANCH} | sed -e "s/\//_/g")
      - docker push quay.io/ukhomeofficedigital/removals-api:d${DRONE_BUILD_NUMBER}
#      - docker push quay.io/ukhomeofficedigital/removals-api:${DOCKER_BRANCH}


services:
  dind:
    image: docker:1-dind
    privileged: true
    command:
      - "-s"
      - "overlay"

#DRONE_JOB_NUMBER

#export PATH=${PATH}:/root/.dvm/bin/docker/1.10.3/
#export DOCKER_BRANCH=$(echo $DRONE_BRANCH | sed -e "s/\//_/g")
#docker build -t $REGISTRY/$PROJECT-$NAME:b$BUILD_NUMBER .
#docker push $REGISTRY/$PROJECT-$NAME:b$BUILD_NUMBER
#docker tag  $REGISTRY/$PROJECT-$NAME:b$BUILD_NUMBER $REGISTRY/$PROJECT-$NAME:$DOCKER_BRANCH
#docker push $REGISTRY/$PROJECT-$NAME:$DOCKER_BRANCH

