pipeline:
  build:
    image: docker:1
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
      - DOCKER_BRANCH=$(echo $DRONE_BRANCH | sed -e "s/\//_/g")
    commands:
      - docker build -t removals-api:b$${DRONE_JOB_NUMBER}-$DRONE_BUILD_NUMBER .

services:
  dind:
    image: docker:1-dind
    privileged: true
    command:
      - "-s"
      - "overlay"

#DRONE_JOB_NUMBER

#export PATH=${PATH}:/root/.dvm/bin/docker/1.10.3/
#export DOCKER_BRANCH=$(echo $DRONE_BRANCH | sed -e "s/\//_/g")
#docker build -t $REGISTRY/$PROJECT-$NAME:b$BUILD_NUMBER .
#docker push $REGISTRY/$PROJECT-$NAME:b$BUILD_NUMBER
#docker tag  $REGISTRY/$PROJECT-$NAME:b$BUILD_NUMBER $REGISTRY/$PROJECT-$NAME:$DOCKER_BRANCH
#docker push $REGISTRY/$PROJECT-$NAME:$DOCKER_BRANCH
#docker rmi  $REGISTRY/$PROJECT-$NAME:b$BUILD_NUMBER
#docker rmi  $REGISTRY/$PROJECT-$NAME:$DOCKER_BRANCH

