verbose: false
instrumentation:
    default-excludes: true
    excludes: ["test/**", "config/**"]
    variable: __coverage__
    compact: true
reporting:
    print: summary
    reports:
        - lcov
        - text-summary
    dir: ./coverage
    watermarks:
        statements: [98, 99]
        lines: [98, 99]
        functions: [98, 99]
        branches: [98, 99]
check:
    global:
        statements: 98
        lines: 98
        branches: 98
        functions: 98
        excludes: []
    each:
        statements: 95
        lines: 95
        branches: 95
        functions: 95
        excludes: []
