version: '2'
services:
  waiter:
    image: martin/wait
  app:
    build: .
    environment:
      - NODE_ENV=production
      - PORT=8000
      - DBHOST=mysql
      - DBPORT=3306
      - DBUSER=root
      - DBPASS=root
      - DBNAME=removals
      - REDIS_SERVICE_HOST=redis
      - REDIS_SERVICE_PORT=6379
    depends_on:
      - mysql
      - redis
      - waiter
    ports:
      - "8000:8000"

  redis:
    image: redis
    ports:
      - "6379:6379"
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=removals
      - MYSQL_ROOT_PASSWORD=root
#      MYSQL_USER: removalsuser
#      MYSQL_PASS: removalspass
