function chicken.js(locals) {
var jade_debug = [{ lineno: 1, filename: "centre_panel.jade" }];
try {
var buf = [];
var jade_mixins = {};
var jade_interp;
;var locals_for_with = (locals || {});(function (Date, centre, moment) {
jade_debug.unshift({ lineno: 0, filename: "centre_panel.jade" });
jade_debug.unshift({ lineno: 1, filename: "centre_panel.jade" });
buf.push("<li" + (jade.attr("id", centre.slug, true, false)) + " class=\"panel\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 2, filename: "centre_panel.jade" });
buf.push("<div class=\"topper\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 3, filename: "centre_panel.jade" });
buf.push("<span class=\"caption\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 3, filename: jade_debug[0].filename });
buf.push("Total");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 4, filename: "centre_panel.jade" });
if ( centre.capacity_female)
{
jade_debug.unshift({ lineno: 5, filename: "centre_panel.jade" });
jade_debug.unshift({ lineno: 5, filename: "centre_panel.jade" });
buf.push("<span class=\"value female\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 5, filename: jade_debug[0].filename });
buf.push("Female " + (jade.escape((jade_interp = centre.capacity_female) == null ? '' : jade_interp)) + "");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
}
jade_debug.shift();
jade_debug.unshift({ lineno: 6, filename: "centre_panel.jade" });
buf.push("<span class=\"value\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 6, filename: jade_debug[0].filename });
buf.push("Male " + (jade.escape((jade_interp = centre.capacity) == null ? '' : jade_interp)) + "");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 9, filename: "centre_panel.jade" });
buf.push("<h2>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 9, filename: jade_debug[0].filename });
buf.push("" + (jade.escape((jade_interp = centre.name) == null ? '' : jade_interp)) + "");
jade_debug.shift();
jade_debug.shift();
buf.push("</h2>");
jade_debug.shift();
jade_debug.unshift({ lineno: 10, filename: "centre_panel.jade" });
buf.push("<ul class=\"availability\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 11, filename: "centre_panel.jade" });
buf.push("<li class=\"available male\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 11, filename: jade_debug[0].filename });
buf.push("Available male");
jade_debug.shift();
jade_debug.unshift({ lineno: 12, filename: "centre_panel.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 12, filename: jade_debug[0].filename });
buf.push("" + (jade.escape((jade_interp = centre.current_beds_male) == null ? '' : jade_interp)) + "");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 13, filename: "centre_panel.jade" });
buf.push("<li class=\"unavailable\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 13, filename: jade_debug[0].filename });
buf.push("Unavailable");
jade_debug.shift();
jade_debug.unshift({ lineno: 14, filename: "centre_panel.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 14, filename: jade_debug[0].filename });
buf.push("" + (jade.escape((jade_interp = centre.current_beds_ooc) == null ? '' : jade_interp)) + "");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 15, filename: "centre_panel.jade" });
if ( centre.current_beds_female)
{
jade_debug.unshift({ lineno: 16, filename: "centre_panel.jade" });
jade_debug.unshift({ lineno: 16, filename: "centre_panel.jade" });
buf.push("<li class=\"available female\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 16, filename: jade_debug[0].filename });
buf.push("Available female");
jade_debug.shift();
jade_debug.unshift({ lineno: 17, filename: "centre_panel.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 17, filename: jade_debug[0].filename });
buf.push("" + (jade.escape((jade_interp = centre.current_beds_female) == null ? '' : jade_interp)) + "");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.shift();
}
jade_debug.shift();
jade_debug.shift();
buf.push("</ul>");
jade_debug.shift();
jade_debug.unshift({ lineno: 19, filename: "centre_panel.jade" });
buf.push("<div class=\"tailer\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 20, filename: "centre_panel.jade" });
var delta = new Date() - centre.updatedAt
jade_debug.shift();
jade_debug.unshift({ lineno: 21, filename: "centre_panel.jade" });
var fourHoursInMilliseconds = 1000 * 60 * 60 * 4
jade_debug.shift();
jade_debug.unshift({ lineno: 22, filename: "centre_panel.jade" });
if ( centre.updatedAt && delta > fourHoursInMilliseconds)
{
jade_debug.unshift({ lineno: 23, filename: "centre_panel.jade" });
jade_debug.unshift({ lineno: 23, filename: "centre_panel.jade" });
buf.push("<div class=\"inner warning\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 24, filename: "centre_panel.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 24, filename: jade_debug[0].filename });
buf.push("Last updated");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 25, filename: "centre_panel.jade" });
buf.push("<span class=\"value\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 25, filename: jade_debug[0].filename });
buf.push("" + (jade.escape((jade_interp = moment(centre.updatedAt).fromNow()) == null ? '' : jade_interp)) + "");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
}
else
{
jade_debug.unshift({ lineno: 27, filename: "centre_panel.jade" });
jade_debug.unshift({ lineno: 27, filename: "centre_panel.jade" });
buf.push("<div class=\"inner\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 28, filename: "centre_panel.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 28, filename: jade_debug[0].filename });
buf.push("Last updated");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 29, filename: "centre_panel.jade" });
buf.push("<span class=\"value\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 29, filename: jade_debug[0].filename });
buf.push("" + (jade.escape((jade_interp = moment(centre.updatedAt).fromNow()) == null ? '' : jade_interp)) + "");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
}
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 31, filename: "centre_panel.jade" });
buf.push("<table class=\"inout\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 32, filename: "centre_panel.jade" });
buf.push("<tr>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 33, filename: "centre_panel.jade" });
buf.push("<td>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 33, filename: jade_debug[0].filename });
buf.push("Inbound");
jade_debug.shift();
jade_debug.shift();
buf.push("</td>");
jade_debug.shift();
jade_debug.unshift({ lineno: 34, filename: "centre_panel.jade" });
buf.push("<td>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 34, filename: jade_debug[0].filename });
buf.push("Outbound");
jade_debug.shift();
jade_debug.shift();
buf.push("</td>");
jade_debug.shift();
jade_debug.shift();
buf.push("</tr>");
jade_debug.shift();
jade_debug.unshift({ lineno: 35, filename: "centre_panel.jade" });
buf.push("<tr>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 36, filename: "centre_panel.jade" });
buf.push("<td>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 36, filename: jade_debug[0].filename });
buf.push("xx");
jade_debug.shift();
jade_debug.shift();
buf.push("</td>");
jade_debug.shift();
jade_debug.unshift({ lineno: 37, filename: "centre_panel.jade" });
buf.push("<td>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 37, filename: jade_debug[0].filename });
buf.push("yy");
jade_debug.shift();
jade_debug.shift();
buf.push("</td>");
jade_debug.shift();
jade_debug.shift();
buf.push("</tr>");
jade_debug.shift();
jade_debug.shift();
buf.push("</table>");
jade_debug.shift();
jade_debug.unshift({ lineno: 39, filename: "centre_panel.jade" });
buf.push("<ul class=\"availability\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 40, filename: "centre_panel.jade" });
buf.push("<li>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 40, filename: jade_debug[0].filename });
buf.push("Reserved");
jade_debug.shift();
jade_debug.unshift({ lineno: 41, filename: "centre_panel.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 41, filename: jade_debug[0].filename });
buf.push("zz");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.shift();
buf.push("</ul>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.shift();}.call(this,"Date" in locals_for_with?locals_for_with.Date:typeof Date!=="undefined"?Date:undefined,"centre" in locals_for_with?locals_for_with.centre:typeof centre!=="undefined"?centre:undefined,"moment" in locals_for_with?locals_for_with.moment:typeof moment!=="undefined"?moment:undefined));;return buf.join("");
} catch (err) {
  jade.rethrow(err, jade_debug[0].filename, jade_debug[0].lineno, "li(id=centre.slug).panel\n    .topper\n        span.caption Total\n        if centre.capacity_female\n            span.value.female Female #{centre.capacity_female}\n        span.value Male #{centre.capacity}\n\n\n    h2 #{centre.name}\n    ul.availability\n        li.available.male Available male\n            span #{centre.current_beds_male}\n        li.unavailable Unavailable\n            span #{centre.current_beds_ooc}\n        if centre.current_beds_female\n            li.available.female Available female\n                span #{centre.current_beds_female}\n\n    .tailer\n        - var delta = new Date() - centre.updatedAt\n        - var fourHoursInMilliseconds = 1000 * 60 * 60 * 4\n        if centre.updatedAt && delta > fourHoursInMilliseconds\n            .inner.warning\n                span Last updated\n                span.value #{moment(centre.updatedAt).fromNow()}\n        else\n            .inner\n                span Last updated\n                span.value #{moment(centre.updatedAt).fromNow()}\n\n    table.inout\n        tr\n            td Inbound\n            td Outbound\n        tr\n            td xx\n            td yy\n\n    ul.availability\n        li Reserved\n            span zz\n\n\n");
}
}