source 'https://rubygems.org'

group :test do
   gem 'gmail', '0.4.0'
   gem 'compass', '1.0.3'
   gem 'cucumber', '2.0.0'
   gem 'capybara', '2.4.4'
   gem 'rspec', '3.0.0'
   gem 'poltergeist', '1.6.0'
   gem 'selenium-webdriver', '2.45.0'
   gem 'launchy', '2.4.3'
  # gem 'write_xlsx','0.83.0'
  # gem 'roo', '1.13.2'
  # gem 'pdf-reader','1.3.3'
   gem 'faraday', '0.9.1'
   gem 'faraday_middleware','0.9.1'
   gem 'faraday-cookie_jar','0.0.6'
  # gem 'yard-cucumber','2.3.2'
   gem 'activesupport','4.2.3'
   gem 'csv_hasher', '0.1.0'
end

