apiVersion: v1
kind: Service
metadata:
  labels:
    name: removals-app
  name: removals-app
  annotations:
    loadbalancer: |
      80:
        type: http
        vhost: dev-lb-1917621059.eu-west-1.elb.amazonaws.com
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 30001
      port: 3000
  selector:
    name: removals-app
